apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui-service
spec:
  selector:
    app: streamlit-ui
  type: NodePort  # Cambia a ClusterIP si usarás un Ingress Controller
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501