apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  labels:
    app: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
        - name: streamlit
          image: streamlit-app:latest
          imagePullPolicy: Never  # Esto fuerza a usar la imagen local
          ports:
            - containerPort: 8501
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"